basePath: /
definitions:
  controllers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  controllers.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: abdulrahman.hijazy.a@gmail.com
    name: Abdulrahman Hijazy
    url: https://www.linkedin.com/in/abdulrahmanhijazy
  description: This is a sample API for user registration and login.
  license:
    name: Cairo University
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Package Tracking System (PTS-Open Shift) phase 0
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login a user with email and password
      parameters:
      - description: User login data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user with name, email, phone, and password. Returns
        a success message if registration is successful.
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success response message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Missing required fields or invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
swagger: "2.0"
